from __future__ import annotations

from typing import Any


BUILTIN_ARTIFACT_SCHEMAS: dict[str, dict[str, Any]] = {'raw_scan': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
              'title': 'xau_raw_scan',
              'type': 'object',
              'additionalProperties': True,
              'required': ['ts_utc', 'symbol', 'monitor_only', 'source_payloads'],
              'properties': {'ts_utc': {'type': 'string'},
                             'symbol': {'type': 'string'},
                             'monitor_only': {'type': 'boolean', 'const': True},
                             'source_payloads': {'type': 'array',
                                                 'items': {'type': 'object',
                                                           'properties': {'errors': {'type': 'array'},
                                                                          'payload': {'type': ['object',
                                                                                               'array'],
                                                                                      'additionalProperties': True,
                                                                                      'properties': {'ohlcv': {'type': 'object',
                                                                                                               'additionalProperties': True,
                                                                                                               'properties': {'H1': {'type': 'array',
                                                                                                                                     'items': {'type': 'object',
                                                                                                                                               'properties': {'close': {'type': 'number'},
                                                                                                                                                              'high': {'type': 'number'},
                                                                                                                                                              'low': {'type': 'number'},
                                                                                                                                                              'open': {'type': 'number'},
                                                                                                                                                              'tick_volume': {'type': 'number'},
                                                                                                                                                              'ts_utc': {'type': 'string'},
                                                                                                                                                              'volume_type': {'type': 'string'}}}},
                                                                                                                              'M15': {'type': 'array',
                                                                                                                                      'items': {'type': 'object',
                                                                                                                                                'properties': {'close': {'type': 'number'},
                                                                                                                                                               'high': {'type': 'number'},
                                                                                                                                                               'low': {'type': 'number'},
                                                                                                                                                               'open': {'type': 'number'},
                                                                                                                                                               'tick_volume': {'type': 'number'},
                                                                                                                                                               'ts_utc': {'type': 'string'},
                                                                                                                                                               'volume_type': {'type': 'string'}}}},
                                                                                                                              'M5': {'type': 'array',
                                                                                                                                     'items': {'type': 'object',
                                                                                                                                               'properties': {'close': {'type': 'number'},
                                                                                                                                                              'high': {'type': 'number'},
                                                                                                                                                              'low': {'type': 'number'},
                                                                                                                                                              'open': {'type': 'number'},
                                                                                                                                                              'tick_volume': {'type': 'number'},
                                                                                                                                                              'ts_utc': {'type': 'string'},
                                                                                                                                                              'volume_type': {'type': 'string'}}}}}},
                                                                                                     'spread': {'type': 'array',
                                                                                                                'items': {'type': 'object',
                                                                                                                          'properties': {'ask': {'type': 'number'},
                                                                                                                                         'bid': {'type': 'number'},
                                                                                                                                         'spread_points': {'type': 'number'},
                                                                                                                                         'spread_policy': {'type': 'string'},
                                                                                                                                         'ts_utc': {'type': 'string'}}}},
                                                                                                     'volume_policy': {'type': 'string'}},
                                                                                      'items': {'type': 'object',
                                                                                                'properties': {'currency': {'type': 'string'},
                                                                                                               'event_policy': {'type': 'string'},
                                                                                                               'impact': {'type': 'string'},
                                                                                                               'title': {'type': 'string'},
                                                                                                               'ts_utc': {'type': 'string'}}}},
                                                                          'quality_flags': {'type': 'array'},
                                                                          'row_counts': {'type': 'object',
                                                                                         'additionalProperties': True,
                                                                                         'properties': {'ohlcv': {'type': 'object',
                                                                                                                  'additionalProperties': True,
                                                                                                                  'properties': {'H1': {'type': 'integer'},
                                                                                                                                 'M15': {'type': 'integer'},
                                                                                                                                 'M5': {'type': 'integer'}}},
                                                                                                        'spread': {'type': 'integer'}}},
                                                                          'source_id': {'type': 'string'},
                                                                          'status': {'type': 'string'},
                                                                          'symbol': {'type': 'string'},
                                                                          'timeframe': {'type': 'string'},
                                                                          'ts_utc': {'type': 'string'},
                                                                          'row_count': {'type': 'integer'}}}},
                             'quality_flags': {'type': 'array'}}},
 'data_quality': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                  'title': 'xau_data_quality',
                  'type': 'object',
                  'additionalProperties': True,
                  'required': ['ts_utc',
                               'symbol',
                               'monitor_only',
                               'freshness_score',
                               'coverage_score',
                               'schema_score',
                               'source_count',
                               'confidence_cap',
                               'present_timeframes',
                               'errors',
                               'quality_flags'],
                  'properties': {'ts_utc': {'type': 'string'},
                                 'symbol': {'type': 'string'},
                                 'monitor_only': {'type': 'boolean', 'const': True},
                                 'freshness_score': {'type': 'number'},
                                 'coverage_score': {'type': 'number'},
                                 'schema_score': {'type': 'number'},
                                 'source_count': {'type': 'integer'},
                                 'confidence_cap': {'type': 'number'},
                                 'present_timeframes': {'type': 'array',
                                                        'items': {'type': 'string'}},
                                 'errors': {'type': 'array'},
                                 'quality_flags': {'type': 'array', 'items': {'type': 'string'}},
                                 'dispersion_score': {'type': 'number'},
                                 'event_count': {'type': 'integer'},
                                 'missing_field_count': {'type': 'integer'},
                                 'news_risk_flag': {'type': 'boolean'},
                                 'session_completeness': {'type': 'number'},
                                 'spread_stability': {'type': 'number'}}},
 'composite_ohlcv': {'$schema': 'https://json-schema.org/draft/2020-12/schema',
                     'title': 'xau_composite_ohlcv',
                     'type': 'object',
                     'additionalProperties': True,
                     'required': ['ts_utc',
                                  'symbol',
                                  'monitor_only',
                                  'timeframes',
                                  'primary_timeframe',
                                  'bars'],
                     'properties': {'ts_utc': {'type': 'string'},
                                    'symbol': {'type': 'string'},
                                    'monitor_only': {'type': 'boolean', 'const': True},
                                    'timeframes': {'type': 'array', 'items': {'type': 'string'}},
                                    'primary_timeframe': {'type': 'string'},
                                    'bars': {'type': 'array',
                                             'items': {'type': 'object',
                                                       'properties': {'close': {'type': 'number'},
                                                                      'high': {'type': 'number'},
                                                                      'low': {'type': 'number'},
                                                                      'open': {'type': 'number'},
                                                                      'tick_volume': {'type': 'number'},
                                                                      'ts_utc': {'type': 'string'},
                                                                      'volume_type': {'type': 'string'}}}},
                                    'confidence_cap': {'type': 'number'},
                                    'latest_by_timeframe': {'type': 'object',
                                                            'additionalProperties': True,
                                                            'properties': {'H1': {'type': 'object',
                                                                                  'additionalProperties': True,
                                                                                  'properties': {'close': {'type': 'number'},
                                                                                                 'high': {'type': 'number'},
                                                                                                 'low': {'type': 'number'},
                                                                                                 'open': {'type': 'number'},
                                                                                                 'tick_volume': {'type': 'number'},
                                                                                                 'ts_utc': {'type': 'string'},
                                                                                                 'volume_type': {'type': 'string'}}},
                                                                           'M15': {'type': 'object',
                                                                                   'additionalProperties': True,
                                                                                   'properties': {'close': {'type': 'number'},
                                                                                                  'high': {'type': 'number'},
                                                                                                  'low': {'type': 'number'},
                                                                                                  'open': {'type': 'number'},
                                                                                                  'tick_volume': {'type': 'number'},
                                                                                                  'ts_utc': {'type': 'string'},
                                                                                                  'volume_type': {'type': 'string'}}},
                                                                           'M5': {'type': 'object',
                                                                                  'additionalProperties': True,
                                                                                  'properties': {'close': {'type': 'number'},
                                                                                                 'high': {'type': 'number'},
                                                                                                 'low': {'type': 'number'},
                                                                                                 'open': {'type': 'number'},
                                                                                                 'tick_volume': {'type': 'number'},
                                                                                                 'ts_utc': {'type': 'string'},
                                                                                                 'volume_type': {'type': 'string'}}}}},
                                    'median_latest_close': {'type': 'number'},
                                    'mtf_rule': {'type': 'string'},
                                    'quality_flags': {'type': 'array', 'items': {'type': 'string'}},
                                    'timeframe_bars': {'type': 'object',
                                                       'additionalProperties': True,
                                                       'properties': {'H1': {'type': 'array',
                                                                             'items': {'type': 'object',
                                                                                       'properties': {'close': {'type': 'number'},
                                                                                                      'high': {'type': 'number'},
                                                                                                      'low': {'type': 'number'},
                                                                                                      'open': {'type': 'number'},
                                                                                                      'tick_volume': {'type': 'number'},
                                                                                                      'ts_utc': {'type': 'string'},
                                                                                                      'volume_type': {'type': 'string'}}}},
                                                                      'M15': {'type': 'array',
                                                                              'items': {'type': 'object',
                                                                                        'properties': {'close': {'type': 'number'},
                                                                                                       'high': {'type': 'number'},
                                                                                                       'low': {'type': 'number'},
                                                                                                       'open': {'type': 'number'},
                                                                                                       'tick_volume': {'type': 'number'},
                                                                                                       'ts_utc': {'type': 'string'},
                                                                                                       'volume_type': {'type': 'string'}}}},
                                                                      'M5': {'type': 'array',
                                                                             'items': {'type': 'object',
                                                                                       'properties': {'close': {'type': 'number'},
                                                                                                      'high': {'type': 'number'},
                                                                                                      'low': {'type': 'number'},
                                                                                                      'open': {'type': 'number'},
                                                                                                      'tick_volume': {'type': 'number'},
                                                                                                      'ts_utc': {'type': 'string'},
                                                                                                      'volume_type': {'type': 'string'}}}}}},
                                    'volume_policy': {'type': 'string'}}},
 'session_context': {'type': 'object',
                     'additionalProperties': True,
                     'required': ['ts_utc',
                                  'symbol',
                                  'monitor_only',
                                  'session_state',
                                  'primary_timeframe',
                                  'session_ranges',
                                  'confidence_cap',
                                  'quality_flags'],
                     'properties': {'ts_utc': {'type': 'string'},
                                    'symbol': {'type': 'string'},
                                    'monitor_only': {'type': 'boolean', 'const': True},
                                    'session_state': {'type': 'string'},
                                    'primary_timeframe': {'type': 'string'},
                                    'session_ranges': {'type': 'object',
                                                       'properties': {'ASIA': {'type': 'object',
                                                                               'additionalProperties': True,
                                                                               'properties': {'bar_count': {'type': 'integer'},
                                                                                              'high': {'type': 'number'},
                                                                                              'last_close': {'type': 'number'},
                                                                                              'low': {'type': 'number'},
                                                                                              'range_points': {'type': 'number'}}},
                                                                      'LONDON': {'type': 'object',
                                                                                 'additionalProperties': True,
                                                                                 'properties': {'bar_count': {'type': 'integer'},
                                                                                                'high': {'type': 'number'},
                                                                                                'last_close': {'type': 'number'},
                                                                                                'low': {'type': 'number'},
                                                                                                'range_points': {'type': 'number'}}},
                                                                      'OFF_SESSION': {'type': 'object',
                                                                                      'additionalProperties': True,
                                                                                      'properties': {'bar_count': {'type': 'integer'},
                                                                                                     'high': {'type': 'number'},
                                                                                                     'last_close': {'type': 'number'},
                                                                                                     'low': {'type': 'number'},
                                                                                                     'range_points': {'type': 'number'}}}}},
                                    'confidence_cap': {'type': 'number'},
                                    'quality_flags': {'type': 'array', 'items': {'type': 'string'}},
                                    'handoff_state': {'type': 'string'}}},
 'macro_pressure': {'type': 'object',
                    'additionalProperties': True,
                    'required': ['ts_utc',
                                 'symbol',
                                 'monitor_only',
                                 'pressure_state',
                                 'drivers',
                                 'confidence_cap',
                                 'quality_flags'],
                    'properties': {'ts_utc': {'type': 'string'},
                                   'symbol': {'type': 'string'},
                                   'monitor_only': {'type': 'boolean', 'const': True},
                                   'pressure_state': {'type': 'string'},
                                   'drivers': {'type': 'array'},
                                   'confidence_cap': {'type': 'number'},
                                   'quality_flags': {'type': 'array', 'items': {'type': 'string'}},
                                   'note': {'type': 'string'}}},
 'event_risk': {'type': 'object',
                'additionalProperties': True,
                'required': ['ts_utc',
                             'symbol',
                             'monitor_only',
                             'risk_state',
                             'event_count',
                             'high_impact_events',
                             'near_high_impact_events',
                             'confidence_cap',
                             'quality_flags'],
                'properties': {'ts_utc': {'type': 'string'},
                               'symbol': {'type': 'string'},
                               'monitor_only': {'type': 'boolean', 'const': True},
                               'risk_state': {'type': 'string'},
                               'event_count': {'type': 'integer'},
                               'high_impact_events': {'type': 'array',
                                                      'items': {'type': 'object',
                                                                'properties': {'currency': {'type': 'string'},
                                                                               'event_policy': {'type': 'string'},
                                                                               'impact': {'type': 'string'},
                                                                               'title': {'type': 'string'},
                                                                               'ts_utc': {'type': 'string'}}}},
                               'near_high_impact_events': {'type': 'array'},
                               'confidence_cap': {'type': 'number'},
                               'quality_flags': {'type': 'array', 'items': {'type': 'string'}},
                               'note': {'type': 'string'}}},
 'state': {'type': 'object',
           'additionalProperties': True,
           'required': ['ts_utc',
                        'symbol',
                        'monitor_only',
                        'state',
                        'summary',
                        'evidence',
                        'quality'],
           'properties': {'ts_utc': {'type': 'string'},
                          'symbol': {'type': 'string'},
                          'monitor_only': {'const': True, 'type': 'boolean'},
                          'state': {'type': 'string'},
                          'summary': {'type': 'string'},
                          'evidence': {'type': 'array', 'items': {'type': 'string'}},
                          'quality': {'type': 'object',
                                      'properties': {'confidence_cap': {'type': 'number'},
                                                     'missing_field_count': {'type': 'integer'},
                                                     'quality_flags': {'type': 'array',
                                                                       'items': {'type': 'string'}},
                                                     'source_count': {'type': 'integer'}}}}},
 'user_insight': {'type': 'object',
                  'additionalProperties': True,
                  'required': ['ts_utc',
                               'symbol',
                               'monitor_only',
                               'headline',
                               'now_read',
                               'operator_focus',
                               'evidence_map',
                               'useful_limits',
                               'upgrade_requirements',
                               'quality_flags'],
                  'properties': {'ts_utc': {'type': 'string'},
                                 'symbol': {'type': 'string'},
                                 'monitor_only': {'const': True, 'type': 'boolean'},
                                 'headline': {'type': 'string'},
                                 'now_read': {'type': 'string'},
                                 'operator_focus': {'type': 'array', 'items': {'type': 'string'}},
                                 'evidence_map': {'type': 'array', 'items': {'type': 'string'}},
                                 'useful_limits': {'type': 'array', 'items': {'type': 'string'}},
                                 'upgrade_requirements': {'type': 'array',
                                                          'items': {'type': 'string'}},
                                 'quality_flags': {'type': 'array', 'items': {'type': 'string'}}}},
 'artifact_quality': {'type': 'object',
                      'additionalProperties': True,
                      'required': ['ts_utc',
                                   'symbol',
                                   'monitor_only',
                                   'status',
                                   'quality_score',
                                   'quality_grade',
                                   'source_count',
                                   'warnings',
                                   'errors',
                                   'confidence_cap'],
                      'properties': {'ts_utc': {'type': 'string'},
                                     'symbol': {'type': 'string'},
                                     'monitor_only': {'const': True, 'type': 'boolean'},
                                     'status': {'type': 'string'},
                                     'quality_score': {'type': 'number'},
                                     'quality_grade': {'type': 'string'},
                                     'source_count': {'type': 'integer'},
                                     'warnings': {'type': 'array', 'items': {'type': 'string'}},
                                     'errors': {'type': 'array'},
                                     'confidence_cap': {'type': 'number'},
                                     'coverage_score': {'type': 'number'},
                                     'event_score': {'type': 'number'},
                                     'freshness_score': {'type': 'number'},
                                     'schema_score': {'type': 'number'},
                                     'session_score': {'type': 'number'},
                                     'spread_score': {'type': 'number'}}},
 'context_summary': {'type': 'object',
                     'additionalProperties': True,
                     'required': ['ts_utc',
                                  'symbol',
                                  'monitor_only',
                                  'latest_close',
                                  'spread_state',
                                  'event_risk_state',
                                  'quality_status',
                                  'quality_grade',
                                  'confidence_cap',
                                  'confidence_explanation',
                                  'monitor_focus',
                                  'limitations',
                                  'quality_flags'],
                     'properties': {'ts_utc': {'type': 'string'},
                                    'symbol': {'type': 'string'},
                                    'monitor_only': {'type': 'boolean', 'const': True},
                                    'latest_close': {'type': ['number', 'null']},
                                    'spread_state': {'type': 'string'},
                                    'event_risk_state': {'type': 'string'},
                                    'quality_status': {'type': 'string'},
                                    'quality_grade': {'type': 'string'},
                                    'confidence_cap': {'type': 'number'},
                                    'confidence_explanation': {'type': 'array',
                                                               'items': {'type': 'string'}},
                                    'monitor_focus': {'type': 'array', 'items': {'type': 'string'}},
                                    'limitations': {'type': 'array', 'items': {'type': 'string'}},
                                    'quality_flags': {'type': 'array', 'items': {'type': 'string'}},
                                    'freshness_age_minutes': {'type': 'number'},
                                    'nearest_session_level': {'type': 'object',
                                                              'additionalProperties': True,
                                                              'properties': {'distance_points': {'type': 'number'},
                                                                             'level': {'type': 'string'},
                                                                             'price': {'type': 'number'},
                                                                             'session': {'type': 'string'}}}}}}
