from __future__ import annotations

from typing import Any


BUILTIN_ARTIFACT_SCHEMAS: dict[str, dict[str, Any]] = {
    "raw_scan": {
        "type": "object",
        "additionalProperties": True,
        "required": ["ts_utc", "symbol", "monitor_only", "source_payloads"],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "source_payloads": {"type": "array"},
        },
    },
    "data_quality": {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "ts_utc",
            "symbol",
            "monitor_only",
            "freshness_score",
            "coverage_score",
            "schema_score",
            "source_count",
            "confidence_cap",
            "present_timeframes",
            "errors",
            "quality_flags",
        ],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "freshness_score": {"type": "number"},
            "coverage_score": {"type": "number"},
            "schema_score": {"type": "number"},
            "source_count": {"type": "integer"},
            "confidence_cap": {"type": "number"},
            "present_timeframes": {"type": "array"},
            "errors": {"type": "array"},
            "quality_flags": {"type": "array"},
        },
    },
    "composite_ohlcv": {
        "type": "object",
        "additionalProperties": True,
        "required": ["ts_utc", "symbol", "monitor_only", "timeframes", "primary_timeframe", "bars"],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "timeframes": {"type": "array"},
            "primary_timeframe": {"type": "string"},
            "bars": {"type": "array"},
        },
    },
    "session_context": {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "ts_utc",
            "symbol",
            "monitor_only",
            "session_state",
            "primary_timeframe",
            "session_ranges",
            "confidence_cap",
            "quality_flags",
        ],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "session_state": {"type": "string"},
            "primary_timeframe": {"type": "string"},
            "session_ranges": {},
            "confidence_cap": {"type": "number"},
            "quality_flags": {"type": "array"},
        },
    },
    "macro_pressure": {
        "type": "object",
        "additionalProperties": True,
        "required": ["ts_utc", "symbol", "monitor_only", "pressure_state", "drivers", "confidence_cap", "quality_flags"],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "pressure_state": {"type": "string"},
            "drivers": {"type": "array"},
            "confidence_cap": {"type": "number"},
            "quality_flags": {"type": "array"},
        },
    },
    "event_risk": {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "ts_utc",
            "symbol",
            "monitor_only",
            "risk_state",
            "event_count",
            "high_impact_events",
            "near_high_impact_events",
            "confidence_cap",
            "quality_flags",
        ],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "risk_state": {"type": "string"},
            "event_count": {"type": "integer"},
            "high_impact_events": {"type": "array"},
            "near_high_impact_events": {"type": "array"},
            "confidence_cap": {"type": "number"},
            "quality_flags": {"type": "array"},
        },
    },
    "state": {
        "type": "object",
        "additionalProperties": True,
        "required": ["ts_utc", "symbol", "monitor_only", "state", "summary", "evidence", "quality"],
        "properties": {
            "ts_utc": {},
            "symbol": {},
            "monitor_only": {"const": True},
            "state": {},
            "summary": {},
            "evidence": {},
            "quality": {},
        },
    },
    "user_insight": {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "ts_utc",
            "symbol",
            "monitor_only",
            "headline",
            "now_read",
            "operator_focus",
            "evidence_map",
            "useful_limits",
            "upgrade_requirements",
            "quality_flags",
        ],
        "properties": {
            "ts_utc": {},
            "symbol": {},
            "monitor_only": {"const": True},
            "headline": {},
            "now_read": {},
            "operator_focus": {},
            "evidence_map": {},
            "useful_limits": {},
            "upgrade_requirements": {},
            "quality_flags": {},
        },
    },
    "artifact_quality": {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "ts_utc",
            "symbol",
            "monitor_only",
            "status",
            "quality_score",
            "quality_grade",
            "source_count",
            "warnings",
            "errors",
            "confidence_cap",
        ],
        "properties": {
            "ts_utc": {},
            "symbol": {},
            "monitor_only": {"const": True},
            "status": {},
            "quality_score": {"type": "number"},
            "quality_grade": {},
            "source_count": {},
            "warnings": {},
            "errors": {},
            "confidence_cap": {},
        },
    },
    "context_summary": {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "ts_utc",
            "symbol",
            "monitor_only",
            "latest_close",
            "spread_state",
            "event_risk_state",
            "quality_status",
            "quality_grade",
            "confidence_cap",
            "confidence_explanation",
            "monitor_focus",
            "limitations",
            "quality_flags",
        ],
        "properties": {
            "ts_utc": {"type": "string"},
            "symbol": {"type": "string"},
            "monitor_only": {"type": "boolean", "const": True},
            "latest_close": {"type": ["number", "null"]},
            "spread_state": {"type": "string"},
            "event_risk_state": {"type": "string"},
            "quality_status": {"type": "string"},
            "quality_grade": {"type": "string"},
            "confidence_cap": {"type": "number"},
            "confidence_explanation": {"type": "array"},
            "monitor_focus": {"type": "array"},
            "limitations": {"type": "array"},
            "quality_flags": {"type": "array"},
        },
    },
}
